import Navbar from "@/components/layout/Navbar";
import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";
import {Providers} from "@/components/layout/Providers";
import {auth} from "@/auth";
import {SessionProvider} from "next-auth/react";


const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	                                         children,
                                         }: Readonly<{
	children: ReactNode;
}>) {
	const session = await auth();

	return (

		<SessionProvider session={session}>
			<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
			<Providers>

				<div className="mx-auto max-w-screen-lg h-screen flex flex-col">
					<Navbar/>
					<div className="flex-grow">{children}</div>
				</div>
			</Providers>
			</body>
			</html>
		</SessionProvider>
	);
}
